#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ln -s $DIR/.vimrc ~
ln -s $DIR/.gvimrc ~

git clone https://github.com/jpo/vim-railscasts-theme.git ~/.vim/railscasts
mkdir ~/.vim/colors
ln -s ~/.vim/railscasts/colors/railscasts.vim ~/.vim/colors/
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
vim -c :BundleInstall

# Install command-t
cd ~/.vim/bundle/command-t/ruby/command-t
ruby extconf.rb
make
cd -

