#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

shopt -s extglob
mkdir ~/scripts
cp $DIR/!(install) ~/scripts

echo 'PATH=$PATH:$HOME/scripts' >> ~/.bashext

ln -s /usr/bin/ack-grep ~/scripts/ack

