#!/bin/bash
LUKSOPTIONS="--allow-discards"
MOUNTOPTIONS="noatime,discard"

sudo cryptsetup luksOpen $LUKSOPTIONS $CRYPTODATADEV cryptodata
sudo mount -o $MOUNTOPTIONS /dev/mapper/cryptodata /media/cryptodata
cd /media/cryptodata/
HISTFILE=/media/cryptodata/.bash_history
export HISTFILE
bash
