#!/usr/bin/env python

import sys
import subprocess
import math
import re

runs = 30

command = "/usr/bin/time --quiet -f %%e %s 2>&1 1> /dev/null" % sys.argv[1]

sum = 0
sum_2 = 0
for _ in xrange(runs):
  output = subprocess.check_output(["/bin/bash", "-c", command])
  time_str = re.search("(\d+\.\d+)$", output).group(0)
  print intern(time_str)
  try:
    time = float(time_str)
  except ValueError:
    continue
  sum += time
  sum_2 += pow(time, 2)

mean = sum / runs
stddev = math.sqrt((sum_2 / runs) - pow(mean, 2))
print("Runs: %d\nMean: %f\nStddev: %f" % (runs, mean, stddev))

