#!/bin/bash
# Mount encrypted directory on UbuntuOne

HISTFILE=
export HISTFILE

DIR=/home/$USER/Ubuntu\ One/encrypted2
DECRYPTED_DIR=/home/$USER/decrypted
MOUNT_OPTIONS="ecryptfs_key_bytes=16,ecryptfs_cipher=aes,ecryptfs_enable_filename_crypto=y,ecryptfs_unlink_sigs,ecryptfs_passthrough=n"

if [ ! -e "$DIR" ] 
then
  mkdir "$DIR"
fi

sudo mount -t ecryptfs -o $MOUNT_OPTIONS "$DIR" "$DECRYPTED_DIR" && cd "$DECRYPTED_DIR" && bash

