#!/bin/bash
# Mount encrypted directory on UbuntuOne

DIR=/home/$USER/Ubuntu\ One/encrypted
MOUNTOPTIONS="ecryptfs_key_bytes=16,ecryptfs_cipher=aes,ecryptfs_enable_filename_crypto=y,ecryptfs_unlink_sigs,ecryptfs_passthrough=n"

if [ ! -e "$DIR" ] 
then
  mkdir "$DIR"
fi

sudo mount -t ecryptfs -o $MOUNTOPTIONS "$DIR" "$DIR"
cd "$DIR"

