#!/bin/bash

sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"
sudo add-apt-repository ppa:skype-wrapper/ppa && sudo apt-get update
sudo apt-get -y install skype skype-wrapper
