#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BASHFILE=~/.bashrc

ln -s $DIR/bash/.[a-z]* ~
# TODO: check if source .bash_xxx already exists before adding it
ls -a $DIR/bash/.[a-z]* | xargs -n1 -I {} bash -c "echo source \`basename {}\` >> $BASHFILE"
